[phases.setup]
nixPkgs = ["nodejs_20"]
cmds = ["npm i -g bun"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "npx serve dist -s -l 3000"
